// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GoogleServiciesConstants
{
        public const string leaderboard_14th_level_leaderboard = "CgkI_JWevbgOEAIQDg"; // <GPGSID>
        public const string leaderboard_24th_level_leaderboard = "CgkI_JWevbgOEAIQGA"; // <GPGSID>
        public const string leaderboard_5th_level_leaderboard = "CgkI_JWevbgOEAIQBQ"; // <GPGSID>
        public const string leaderboard_19th_level_leaderboard = "CgkI_JWevbgOEAIQEw"; // <GPGSID>
        public const string achievement_mesas = "CgkI_JWevbgOEAIQHw"; // <GPGSID>
        public const string leaderboard_11th_level_leaderboard = "CgkI_JWevbgOEAIQCw"; // <GPGSID>
        public const string leaderboard_8th_level_leaderboard = "CgkI_JWevbgOEAIQCA"; // <GPGSID>
        public const string achievement_long_way_to_home = "CgkI_JWevbgOEAIQJA"; // <GPGSID>
        public const string leaderboard_12th_level_leaderboard = "CgkI_JWevbgOEAIQDA"; // <GPGSID>
        public const string leaderboard_22nd_level_leaderboard = "CgkI_JWevbgOEAIQFg"; // <GPGSID>
        public const string achievement_i_fell_home = "CgkI_JWevbgOEAIQIg"; // <GPGSID>
        public const string achievement_boundless_forest = "CgkI_JWevbgOEAIQHQ"; // <GPGSID>
        public const string leaderboard_25th_level_leaderboard = "CgkI_JWevbgOEAIQGQ"; // <GPGSID>
        public const string achievement_dark_cave = "CgkI_JWevbgOEAIQHg"; // <GPGSID>
        public const string leaderboard_15th_level_leaderboard = "CgkI_JWevbgOEAIQDw"; // <GPGSID>
        public const string leaderboard_2nd_level_leaderboard = "CgkI_JWevbgOEAIQAg"; // <GPGSID>
        public const string achievement_red_forest = "CgkI_JWevbgOEAIQHA"; // <GPGSID>
        public const string leaderboard_13th_level_leaderboard = "CgkI_JWevbgOEAIQDQ"; // <GPGSID>
        public const string achievement_first_successful_landing = "CgkI_JWevbgOEAIQGg"; // <GPGSID>
        public const string leaderboard_6th_level_leaderboard = "CgkI_JWevbgOEAIQBg"; // <GPGSID>
        public const string leaderboard_9th_level_leaderboard = "CgkI_JWevbgOEAIQCQ"; // <GPGSID>
        public const string achievement_through_clouds = "CgkI_JWevbgOEAIQGw"; // <GPGSID>
        public const string achievement_home_sweet_home = "CgkI_JWevbgOEAIQIw"; // <GPGSID>
        public const string leaderboard_23th_level_leaderboard = "CgkI_JWevbgOEAIQFw"; // <GPGSID>
        public const string leaderboard_21st_level_leaderboard = "CgkI_JWevbgOEAIQFQ"; // <GPGSID>
        public const string achievement_hills_labyrinth = "CgkI_JWevbgOEAIQIA"; // <GPGSID>
        public const string leaderboard_18th_level_leaderboard = "CgkI_JWevbgOEAIQEg"; // <GPGSID>
        public const string leaderboard_16th_level_leaderboard = "CgkI_JWevbgOEAIQEA"; // <GPGSID>
        public const string leaderboard_10th_level_leaderboard = "CgkI_JWevbgOEAIQCg"; // <GPGSID>
        public const string leaderboard_1st_level_leaderboard = "CgkI_JWevbgOEAIQAQ"; // <GPGSID>
        public const string leaderboard_17th_level_leaderboard = "CgkI_JWevbgOEAIQEQ"; // <GPGSID>
        public const string leaderboard_7th_level_leaderboard = "CgkI_JWevbgOEAIQBw"; // <GPGSID>
        public const string leaderboard_3rd_level_leaderboard = "CgkI_JWevbgOEAIQAw"; // <GPGSID>
        public const string leaderboard_4th_level_leaderboard = "CgkI_JWevbgOEAIQBA"; // <GPGSID>
        public const string achievement_return_to_space = "CgkI_JWevbgOEAIQIQ"; // <GPGSID>
        public const string leaderboard_20th_level_leaderboard = "CgkI_JWevbgOEAIQFA"; // <GPGSID>

}

